-- Real prices, sizes and descriptions, from Beco.
--
-- Two sources, both supplied by Irene on 1 September 2026:
--   * "Beco Product Data (fill in what you know)", the sheet sent in week 1,
--     returned with a price and a slab size for all 24 stones.
--   * "12MM Sintered Stone Descriptions.docx", carrying prose, finish, body
--     composition and face type for 22 of them.
--
-- This is the change that turns a gallery into a catalogue. A9 assumed
-- everything would launch POA because no price data existed anywhere; it now
-- does, so the stones move to fixed pricing and in stock.
--
-- The importer no longer touches these columns, per the fix that stopped it
-- rewriting commercial fields on every run, so a nightly Drive sync cannot
-- undo any of it.

create temporary table product_data (
  slug        text primary key,
  price       numeric(12,2),
  description text,
  short_desc  text,
  specs       jsonb,
  face        text
) on commit preserve rows;

insert into product_data (slug, price, description, short_desc, specs, face) values
  ('amber-jade', 65000, 'Warm taupe, greige and amber tones run in soft vertical layers across the surface, creating the calm, natural look of onyx. A sophisticated choice for spaces that call for warmth, texture and understated luxury.', 'Warm taupe, greige and amber tones run in soft vertical layers across the surface, creating the calm, natural look of onyx.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Polished", "Body composition": "Super White Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('beverly-gold', 65000, 'A soft off-white background is crossed by delicate grey and warm ochre veins. Light and elegant, Beverly Gold creates a bright, welcoming feel while adding just the right amount of movement to a luxury interior.', 'A soft off-white background is crossed by delicate grey and warm ochre veins.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Polished", "Body composition": "Super White Full Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'book_match'),
  ('bianco-fendi', 70000, 'Clean white meets striking grey patterns that move boldly across the surface. Bianco Fendi has a strong architectural character, making it ideal for modern kitchens, statement islands, reception desks and feature walls.', 'Clean white meets striking grey patterns that move boldly across the surface.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Silky", "Body composition": "Super White Full Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'book_match'),
  ('bvlgari', 95000, 'Inspired by the dramatic beauty of Calacatta Viola, Bvlgari combines a brilliant white background with rich burgundy and deep plum movement. Bold, luxurious and fashion-forward, it is designed for interiors that are meant to make a statement.', 'Inspired by the dramatic beauty of Calacatta Viola, Bvlgari combines a brilliant white background with rich burgundy and deep plum movement.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Polished", "Body composition": "Translucent Full Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('calcatta-gold', 60000, 'Elegant grey and warm gold veins sweep diagonally across a brilliant white background. Calcatta Gold offers the timeless beauty of classic marble with a refined, contemporary feel.', 'Elegant grey and warm gold veins sweep diagonally across a brilliant white background.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Polished", "Body composition": "Super White Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'book_match'),
  ('calcatta-oro', 65000, 'A bright white base with bold charcoal-grey and warm gold veins that flow organically across the surface. Dramatic yet elegant, Calcatta Oro brings the look of luxurious Italian marble into sophisticated kitchens, bathrooms and feature spaces.', 'A bright white base with bold charcoal-grey and warm gold veins that flow organically across the surface.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Silky", "Body composition": "Super White Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'book_match'),
  ('cyprus-light-grey', 75000, 'A cool grey background with subtle speckling and natural-looking texture gives Cyprus Light Grey the character of limestone and concrete. Its understated finish works beautifully in contemporary, industrial and minimalist spaces.', 'A cool grey background with subtle speckling and natural-looking texture gives Cyprus Light Grey the character of limestone and concrete.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "3D Digital", "Body composition": "Light Grey Speckled Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('etereo', 65000, 'Soft warm-grey tones blend gently across a clean surface, creating a calm and seamless look. Etereo is perfect for modern interiors where simplicity, warmth and quiet luxury take centre stage.', 'Soft warm-grey tones blend gently across a clean surface, creating a calm and seamless look.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Matte", "Body composition": "Light Grey Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('galaxy-bianco', 65000, 'Soft layers of cream, alabaster and grey flow gently across the surface, inspired by the natural beauty of quartzite and marble. Galaxy Bianco brings light, movement and a sense of calm to refined interiors.', 'Soft layers of cream, alabaster and grey flow gently across the surface, inspired by the natural beauty of quartzite and marble.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Bush Hammered", "Body composition": "Super White Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('jatoba-brown', 85000, 'Deep earthy brown, charcoal and bronze tones are brought to life with delicate white veins. Rich and dramatic, Jatoba Brown adds depth and warmth to sophisticated interiors and is particularly striking in darker, moodier spaces.', 'Deep earthy brown, charcoal and bronze tones are brought to life with delicate white veins.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "3D Digital", "Body composition": "Brown Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('limestone-beige', 70000, 'A warm sandy-beige background is finished with fine natural-looking speckles. Soft and inviting, Limestone Beige brings the relaxed beauty of natural coastal stone into warm, elegant interiors.', 'A warm sandy-beige background is finished with fine natural-looking speckles.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Soft Matte", "Body composition": "Beige Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('limestone-creamy', 65000, 'Warm cream tones are paired with subtle fossil-like detailing and natural variation. Limestone Creamy creates a timeless, Mediterranean feel that works beautifully across kitchens, bathrooms, walls and other refined spaces.', 'Warm cream tones are paired with subtle fossil-like detailing and natural variation.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Bush Hammered", "Body composition": "Super White Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('limestone-ivory', 75000, 'A soft ivory base with barely-there mineral detailing creates a clean and calming surface. Limestone Ivory is ideal for understated luxury, offering warmth without overwhelming the space.', 'A soft ivory base with barely-there mineral detailing creates a clean and calming surface.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Soft Matte", "Body composition": "Super White Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('moire-white', 65000, 'Crisp grey veins sweep boldly across a pure white background, creating the look of classic Italian marble with a modern edge. Moire White is a natural choice for statement islands, vanity tops and feature walls.', 'Crisp grey veins sweep boldly across a pure white background, creating the look of classic Italian marble with a modern edge.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Matte", "Body composition": "Super White Full Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('precious-black', 75000, 'Deep charcoal and rich espresso tones are layered with fine mineral veining, creating a surface full of depth and character. Precious Black brings a sophisticated, dramatic feel to contemporary luxury interiors.', 'Deep charcoal and rich espresso tones are layered with fine mineral veining, creating a surface full of depth and character.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "3D Digital", "Body composition": "Super Black Speckled Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('pure-white', 65000, 'A beautifully clean, bright-white surface with an almost seamless appearance. Pure White is the ultimate choice for minimalist interiors, creating a fresh and timeless foundation that allows the architecture and furnishings to take centre stage.', 'A beautifully clean, bright-white surface with an almost seamless appearance.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Soft Matte", "Body composition": "Super White Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('rome-phantom-ivory', 75000, 'Soft cloud-like movement and subtle travertine-inspired veining flow across a warm ivory background. Rome Phantom Ivory brings a relaxed sense of elegance and natural warmth to contemporary spaces.', 'Soft cloud-like movement and subtle travertine-inspired veining flow across a warm ivory background.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "3D Digital", "Body composition": "Super White Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'book_match'),
  ('sabnis', 75000, 'A deep midnight-black background is crossed by dramatic white veins that move like flashes of light. Sabnis is bold, luxurious and unmistakable, and it is made for statement islands, feature walls and interiors designed to command attention.', 'A deep midnight-black background is crossed by dramatic white veins that move like flashes of light.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "Grip", "Body composition": "Super Black Full Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('sandstone-beige', 75000, 'Soft diagonal grains flow across a warm nude-beige background, creating the natural movement of French sandstone. Sandstone Beige adds warmth and texture while maintaining a clean, sophisticated look.', 'Soft diagonal grains flow across a warm nude-beige background, creating the natural movement of French sandstone.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "3D Digital", "Body composition": "Beige Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('sandstone-ivory', 70000, 'Pale ivory tones meet delicate grain patterns for a surface that feels warm, natural and contemporary. Sandstone Ivory is ideal for creating bright, welcoming spaces with a subtle connection to natural stone.', 'Pale ivory tones meet delicate grain patterns for a surface that feels warm, natural and contemporary.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "3D Digital", "Body composition": "Super White Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face'),
  ('statuario', 65000, null, null, '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', null),
  ('statuario-gold', 65000, null, null, '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', null),
  ('taj-mahal', 75000, null, null, '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', null),
  ('travertine-beige', 75000, 'Soft beige tones and natural-looking layers create the warm, timeless character of classic travertine. Travertine Beige brings a relaxed, earthy elegance to interiors, making it ideal for kitchens, bathrooms, feature walls and spaces designed to feel effortlessly luxurious.', 'Soft beige tones and natural-looking layers create the warm, timeless character of classic travertine.', '{"Slab size": "3200 x 1600 x 12mm", "Thickness": "12mm", "Finish": "3D Digital", "Body composition": "Beige Speckled Body", "Recommended for": "Kitchen countertops, islands, vanity tops, feature walls and reception areas"}', 'one_face')
;

update products p set
  price               = d.price,
  price_display_mode  = 'fixed',
  availability        = 'in_stock',
  unit                = 'per slab',
  description         = coalesce(d.description, p.description),
  short_description   = coalesce(d.short_desc, p.short_description),
  specs               = d.specs,
  -- The descriptions document states the face type explicitly, which is a
  -- better source than the presence of a BOOK MATCH photograph.
  face_type           = coalesce(d.face::face_type, p.face_type)
from product_data d
where p.slug = d.slug;

drop table product_data;
